language: objective-c
xcode_workspace: Example/MKDropdownMenuExample.xcworkspace
xcode_scheme: MKDropdownMenuExample
xcode_sdk: iphonesimulator9.0
osx_image: xcode7
before_script:
  - brew update
  - brew upgrade xctool